BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "perf100" (
	"perfumeId"	INT,
	"url"	TEXT,
	"Perfume"	TEXT,
	"Brand"	TEXT,
	"Country"	TEXT,
	"Gender"	TEXT,
	"Rating"	REAL,
	"Year"	TEXT,
	"Accords"	TEXT,
	"Perfumers"	TEXT
);
INSERT INTO "perf100" VALUES (24063,'https://www.fragrantica.com/perfume/nilafar-du-nil/narmar-extrait-de-parfum-74625.html','narmar-extrait-de-parfum','nilafar-du-nil','Egypt','men',4.93,'2022','aromatic, woody, warm spicy, musky, fresh spicy','unknown');
INSERT INTO "perf100" VALUES (24062,'https://www.fragrantica.com/perfume/parfumerie-bruckner/aoud-no-1-36012.html','aoud-no-1','parfumerie-bruckner','Germany','unisex',4.86,'2011','fruity, sweet, oud, woody, powdery','unknown');
INSERT INTO "perf100" VALUES (24061,'https://www.fragrantica.com/perfume/darkbeat-parfums/khaox-64967.html','khaox','darkbeat-parfums','Spain','unisex',4.85,'2020','green, aromatic, citrus, fresh spicy, woody','jos� m. giraldo');
INSERT INTO "perf100" VALUES (24059,'https://www.fragrantica.com/perfume/o-boticario/floratta-58773.html','floratta','o-boticario','Brazil','women',4.81,'1992','white floral, ozonic, fresh, musky, powdery','thierry lecoule');
INSERT INTO "perf100" VALUES (24060,'https://www.fragrantica.com/perfume/sultan-pasha-attars/cheval-d-arabie-64544.html','cheval-d-arabie','sultan-pasha-attars','UK','unisex',4.81,'2020','rose, amber, fresh spicy, animalic, aromatic','sultan pasha');
INSERT INTO "perf100" VALUES (24058,'https://www.fragrantica.com/perfume/yves-saint-laurent/art-collection-la-nuit-de-l-homme-57678.html','art-collection-la-nuit-de-l-homme','yves-saint-laurent','France','men',4.79,'2014','aromatic, woody, warm spicy, lavender, fresh spicy','unknown');
INSERT INTO "perf100" VALUES (24055,'https://www.fragrantica.com/perfume/o-boticario/clipping-65589.html','clipping','o-boticario','Brazil','unisex',4.77,'2002','fresh spicy, warm spicy, citrus, aromatic, woody','unknown');
INSERT INTO "perf100" VALUES (24056,'https://www.fragrantica.com/perfume/karen-low/xchange-wonderman-57908.html','xchange-wonderman','karen-low','France','men',4.77,'2018','vanilla, fruity, sweet, warm spicy, cinnamon','unknown');
INSERT INTO "perf100" VALUES (24057,'https://www.fragrantica.com/perfume/michael-malul-london/citizen-jack-parfum-87687.html','citizen-jack-parfum','michael-malul-london','USA','men',4.77,'2022','woody, vanilla, powdery, aromatic, amber','clement gavarry');
INSERT INTO "perf100" VALUES (24052,'https://www.fragrantica.com/perfume/afnan/zimaya-wujood-90227.html','zimaya-wujood','afnan','UAE','men',4.76,NULL,'vanilla, fresh spicy, amber, warm spicy, powdery','unknown');
INSERT INTO "perf100" VALUES (24053,'https://www.fragrantica.com/perfume/maison-alhambra/dark-door-intense-94172.html','dark-door-intense','maison-alhambra','UAE','unisex',4.76,'2022','woody, iris, powdery, lavender, aromatic','unknown');
INSERT INTO "perf100" VALUES (24054,'https://www.fragrantica.com/perfume/boadicea-the-victorious/lavish-55772.html','lavish','boadicea-the-victorious','UK','unisex',4.76,'2019','woody, citrus, aromatic, earthy, fresh spicy','unknown');
INSERT INTO "perf100" VALUES (24050,'https://www.fragrantica.com/perfume/narciso-rodriguez/narciso-rodriguez-musc-oil-for-him-47533.html','narciso-rodriguez-musc-oil-for-him','narciso-rodriguez','USA','men',4.75,NULL,'musky, ozonic, aquatic, woody, patchouli','francis kurkdjian');
INSERT INTO "perf100" VALUES (24051,'https://www.fragrantica.com/perfume/fragrance-world/spectre-ghost-94697.html','spectre-ghost','fragrance-world','UAE','men',4.75,'2023','warm spicy, vanilla, woody, citrus, patchouli','unknown');
INSERT INTO "perf100" VALUES (24046,'https://www.fragrantica.com/perfume/roger-gallet/fleurs-d-amour-33690.html','fleurs-d-amour','roger-gallet','France','women',4.74,'1902','woody, citrus, amber, sweet, aromatic','unknown');
INSERT INTO "perf100" VALUES (24047,'https://www.fragrantica.com/perfume/dixit-zak/rising-mysore-57841.html','rising-mysore','dixit-zak','France','unisex',4.74,'2019','warm spicy, citrus, fresh spicy, woody, aromatic','nitish dixit, zakir laskar');
INSERT INTO "perf100" VALUES (24048,'https://www.fragrantica.com/perfume/caron/bellodgia-extrait-34543.html','bellodgia-extrait','caron','France','women',4.74,'1927','warm spicy, floral, powdery, white floral, rose','ernest daltroff');
INSERT INTO "perf100" VALUES (24049,'https://www.fragrantica.com/perfume/afnan/musctique-77451.html','musctique','afnan','UAE','unisex',4.74,'2022','green, musky, warm spicy, aromatic, oud','unknown');
INSERT INTO "perf100" VALUES (24042,'https://www.fragrantica.com/perfume/o-boticario/spirit-of-flowers-38472.html','spirit-of-flowers','o-boticario','Brazil','women',4.73,'1993','floral, white floral, tuberose, rose, green','unknown');
INSERT INTO "perf100" VALUES (24043,'https://www.fragrantica.com/perfume/rasasi/oudh-al-boruzz-rooh-al-assam-45041.html','oudh-al-boruzz-rooh-al-assam','rasasi','UAE','unisex',4.73,'2015','oud, rose, leather, woody, warm spicy','raphael haury');
INSERT INTO "perf100" VALUES (24044,'https://www.fragrantica.com/perfume/arabian-oud/bussma-85160.html','bussma','arabian-oud','Arabia saudi ','men',4.73,'2022','warm spicy, vanilla, metallic, leather, woody','unknown');
INSERT INTO "perf100" VALUES (24045,'https://www.fragrantica.com/perfume/fragrance-world/liquid-brun-94713.html','liquid-brun','fragrance-world','UAE','women',4.73,'2024','sweet, vanilla, warm spicy, musky, cinnamon','unknown');
INSERT INTO "perf100" VALUES (24039,'https://www.fragrantica.com/perfume/zimaya/zukhruf-pink-92571.html','zukhruf-pink','zimaya','UAE','women',4.72,'2023','powdery, vanilla, sweet, almond, woody','unknown');
INSERT INTO "perf100" VALUES (24040,'https://www.fragrantica.com/perfume/ramon-monegal/alhambra-oud-56553.html','alhambra-oud','ramon-monegal','Spain','unisex',4.72,'2019','oud, white floral, amber, fruity, fresh','ramon monegal');
INSERT INTO "perf100" VALUES (24041,'https://www.fragrantica.com/perfume/ermenegildo-zegna/passion-46490.html','passion','ermenegildo-zegna','Italy','men',4.72,'2017','amber, warm spicy, woody, rum, metallic','unknown');
INSERT INTO "perf100" VALUES (24031,'https://www.fragrantica.com/perfume/guerlain/fol-arome-2020-62088.html','fol-arome-2020','guerlain','France','women',4.71,'2020','powdery, floral, aromatic, iris, lavender','thierry wasser');
INSERT INTO "perf100" VALUES (24032,'https://www.fragrantica.com/perfume/jean-paul-gaultier/le-male-collector-edition-2018-51775.html','le-male-collector-edition-2018','jean-paul-gaultier','France','men',4.71,'2018','vanilla, aromatic, amber, lavender, warm spicy','unknown');
INSERT INTO "perf100" VALUES (24033,'https://www.fragrantica.com/perfume/natura/flor-d-agua-56437.html','flor-d-agua','natura','Brazil','women',4.71,'2003','aromatic, marine, herbal, floral, fresh spicy','ver�nica kato');
INSERT INTO "perf100" VALUES (24034,'https://www.fragrantica.com/perfume/o-boticario/fleur-43618.html','fleur','o-boticario','Brazil','women',4.71,'2003','rose, powdery, musky, violet, floral','unknown');
INSERT INTO "perf100" VALUES (24035,'https://www.fragrantica.com/perfume/aaron-terence-hughes/hard-candy-elixir-83712.html','hard-candy-elixir','aaron-terence-hughes','UK','unisex',4.71,'2023','sweet, vanilla, amber, fruity, aromatic','unknown');
INSERT INTO "perf100" VALUES (24036,'https://www.fragrantica.com/perfume/arabian-oud/royal-oud-68298.html','royal-oud','arabian-oud','Arabia saudi ','men',4.71,'2019','woody, animalic, musky, rose, warm spicy','unknown');
INSERT INTO "perf100" VALUES (24037,'https://www.fragrantica.com/perfume/henry-jacques/ambre-cuir-de-hj-43828.html','ambre-cuir-de-hj','henry-jacques','France','women',4.71,'2010','amber, iris, leather, aromatic, powdery','unknown');
INSERT INTO "perf100" VALUES (24038,'https://www.fragrantica.com/perfume/evocative-perfumes/olibanum-29139.html','olibanum','evocative-perfumes','Australia','unisex',4.71,'2014','woody, fresh spicy, aromatic, amber, smoky','mark evans');
INSERT INTO "perf100" VALUES (24023,'https://www.fragrantica.com/perfume/guerlain/mahora-extrait-de-parfum-33610.html','mahora-extrait-de-parfum','guerlain','France','women',4.7,NULL,'white floral, floral, woody, sweet, citrus','jean-paul guerlain');
INSERT INTO "perf100" VALUES (24024,'https://www.fragrantica.com/perfume/jean-paul-gaultier/le-male-collector-s-snow-globe-57184.html','le-male-collector-s-snow-globe','jean-paul-gaultier','France','men',4.7,'2019','aromatic, vanilla, warm spicy, amber, woody','francis kurkdjian');
INSERT INTO "perf100" VALUES (24025,'https://www.fragrantica.com/perfume/maison-alhambra/sceptre-malachite-94163.html','sceptre-malachite','maison-alhambra','UAE','unisex',4.7,'2022','citrus, aromatic, woody, fruity, amber','unknown');
INSERT INTO "perf100" VALUES (24026,'https://www.fragrantica.com/perfume/rasasi/attar-al-boruzz-jazeebiyat-musk-tabriz-75470.html','attar-al-boruzz-jazeebiyat-musk-tabriz','rasasi','UAE','unisex',4.7,'2015','white floral, fruity, tuberose, powdery, musky','unknown');
INSERT INTO "perf100" VALUES (24027,'https://www.fragrantica.com/perfume/rasasi/oudh-al-boruzz-abeer-malaysia-45040.html','oudh-al-boruzz-abeer-malaysia','rasasi','UAE','unisex',4.7,'2015','oud, woody, fresh spicy, earthy, leather','raphael haury');
INSERT INTO "perf100" VALUES (24028,'https://www.fragrantica.com/perfume/yves-saint-laurent/la-nuit-de-l-homme-edition-collector-2014-57674.html','la-nuit-de-l-homme-edition-collector-2014','yves-saint-laurent','France','men',4.7,'2014','aromatic, woody, fresh spicy, warm spicy, lavender','unknown');
INSERT INTO "perf100" VALUES (24029,'https://www.fragrantica.com/perfume/perry-ellis/perry-ellis-midnight-78553.html','perry-ellis-midnight','perry-ellis','USA','men',4.7,'2021','amber, vanilla, citrus, sweet, warm spicy','unknown');
INSERT INTO "perf100" VALUES (24030,'https://www.fragrantica.com/perfume/al-haramain-perfumes/amazing-mukhallath-26558.html','amazing-mukhallath','al-haramain-perfumes','UAE','unisex',4.7,NULL,'amber, aromatic, woody, earthy, warm spicy','unknown');
INSERT INTO "perf100" VALUES (24011,'https://www.fragrantica.com/perfume/estee-lauder/estee-extrait-33614.html','estee-extrait','estee-lauder','France','women',4.69,'1968','white floral, woody, powdery, sweet, floral','bernard chant, betty busse');
INSERT INTO "perf100" VALUES (24012,'https://www.fragrantica.com/perfume/amouage/silver-cristal-43050.html','silver-cristal','amouage','Oman','women',4.69,'1996','woody, powdery, white floral, earthy, mossy','unknown');
INSERT INTO "perf100" VALUES (24013,'https://www.fragrantica.com/perfume/natura/exsultate-33953.html','exsultate','natura','Brazil','women',4.69,'1996','floral, iris, citrus, powdery, violet','ver�nica kato');
INSERT INTO "perf100" VALUES (24014,'https://www.fragrantica.com/perfume/roja-dove/aoud-absolue-precieux-49882.html','aoud-absolue-precieux','roja-dove','UK','unisex',4.69,'2010','citrus, fresh spicy, oud, rose, aromatic','roja dove');
INSERT INTO "perf100" VALUES (24015,'https://www.fragrantica.com/perfume/coty/emeraude-parfum-55500.html','emeraude-parfum','coty','USA','women',4.69,'1921','amber, citrus, woody, balsamic, sweet','francois coty');
INSERT INTO "perf100" VALUES (24016,'https://www.fragrantica.com/perfume/arabian-oud/arabian-leather-76554.html','arabian-leather','arabian-oud','Arabia saudi ','unisex',4.69,NULL,'powdery, iris, musky, earthy, woody','unknown');
INSERT INTO "perf100" VALUES (24017,'https://www.fragrantica.com/perfume/donna-karan/fuel-for-men-13831.html','fuel-for-men','donna-karan','USA','men',4.69,'2008','woody, fruity, sweet, aromatic, floral','unknown');
INSERT INTO "perf100" VALUES (24018,'https://www.fragrantica.com/perfume/henry-jacques/roi-sans-equipage-43872.html','roi-sans-equipage','henry-jacques','France','men',4.69,'2016','aromatic, leather, woody, fresh spicy, citrus','unknown');
INSERT INTO "perf100" VALUES (24019,'https://www.fragrantica.com/perfume/maracuja-brasil/couro-lounge-65888.html','couro-lounge','maracuja-brasil','Brazil','unisex',4.69,'2021','honey, leather, musky, sweet, animalic','iff');
INSERT INTO "perf100" VALUES (24020,'https://www.fragrantica.com/perfume/myrurgia/embrujo-de-sevilla-41048.html','embrujo-de-sevilla','myrurgia','Spain','women',4.69,'1933','amber, fresh, warm spicy, aldehydic, woody','unknown');
INSERT INTO "perf100" VALUES (24021,'https://www.fragrantica.com/perfume/pierre-balmain/vent-vert-the-original-50444.html','vent-vert-the-original','pierre-balmain','France','women',4.69,'1947','green, fresh spicy, aromatic, floral, white floral','germaine cellier');
INSERT INTO "perf100" VALUES (24022,'https://www.fragrantica.com/perfume/the-spirit-of-dubai/diwan-44154.html','diwan','the-spirit-of-dubai','UAE','unisex',4.69,'2017','amber, smoky, woody, oud, rose','unknown');
INSERT INTO "perf100" VALUES (24003,'https://www.fragrantica.com/perfume/guerlain/habit-rouge-dress-code-2016-40599.html','habit-rouge-dress-code-2016','guerlain','France','men',4.68,'2016','sweet, vanilla, leather, rose, citrus','thierry wasser');
INSERT INTO "perf100" VALUES (24004,'https://www.fragrantica.com/perfume/valentino/valentino-uomo-intense-2021-75094.html','valentino-uomo-intense-2021','valentino','Italy','men',4.68,'2021','vanilla, iris, powdery, leather, aromatic','unknown');
INSERT INTO "perf100" VALUES (24005,'https://www.fragrantica.com/perfume/granado/folha-imperial-70585.html','folha-imperial','granado','Brazil','unisex',4.68,'2021','citrus, aromatic, green, woody, earthy','carmita magalhaes');
INSERT INTO "perf100" VALUES (24006,'https://www.fragrantica.com/perfume/aaron-terence-hughes/addicted-92928.html','addicted','aaron-terence-hughes','UK','unisex',4.68,'2024','warm spicy, sweet, chocolate, woody, honey','unknown');
INSERT INTO "perf100" VALUES (24007,'https://www.fragrantica.com/perfume/arabian-oud/diwan-71858.html','diwan','arabian-oud','Arabia saudi ','unisex',4.68,'2020','musky, fresh spicy, woody, amber, warm spicy','unknown');
INSERT INTO "perf100" VALUES (24008,'https://www.fragrantica.com/perfume/claude-marsal-parfums/la-melodie-49852.html','la-melodie','claude-marsal-parfums','USA','men',4.68,'2016','woody, whiskey, warm spicy, marine, patchouli','unknown');
INSERT INTO "perf100" VALUES (24009,'https://www.fragrantica.com/perfume/mith/mystery-for-him-88287.html','mystery-for-him','mith','Thailand','unisex',4.68,'2023','citrus, aromatic, vanilla, woody, soft spicy','jean-christophe h�rault');
INSERT INTO "perf100" VALUES (24010,'https://www.fragrantica.com/perfume/michael-malul-london/west-loop-87587.html','west-loop','michael-malul-london','USA','men',4.68,'2023','floral, amber, sweet, warm spicy, woody','gabriela chelariu');
INSERT INTO "perf100" VALUES (23997,'https://www.fragrantica.com/perfume/guerlain/l-heure-bleue-extract-33602.html','l-heure-bleue-extract','guerlain','France','women',4.67,'1912','powdery, violet, vanilla, iris, warm spicy','jacques guerlain');
INSERT INTO "perf100" VALUES (23998,'https://www.fragrantica.com/perfume/guerlain/muguet-millesime-2020-60495.html','muguet-millesime-2020','guerlain','France','unisex',4.67,'2020','green, white floral, fresh, floral','thierry wasser');
INSERT INTO "perf100" VALUES (23999,'https://www.fragrantica.com/perfume/roja-dove/amber-aoud-absolue-precieux-41900.html','amber-aoud-absolue-precieux','roja-dove','UK','unisex',4.67,'2012','citrus, rose, patchouli, woody, warm spicy','roja dove');
INSERT INTO "perf100" VALUES (24000,'https://www.fragrantica.com/perfume/pierre-balmain/monsieur-balmain-64628.html','monsieur-balmain','pierre-balmain','France','men',4.67,'1964','citrus, fresh spicy, aromatic, warm spicy, herbal','germaine cellier');
INSERT INTO "perf100" VALUES (24001,'https://www.fragrantica.com/perfume/bogue/ag-70057.html','ag','bogue','Italy','unisex',4.67,'2021','woody, aromatic, amber, white floral, fresh spicy','antonio gardoni');
INSERT INTO "perf100" VALUES (24002,'https://www.fragrantica.com/perfume/al-haramain-perfumes/obsessive-oudh-26559.html','obsessive-oudh','al-haramain-perfumes','UAE','unisex',4.67,NULL,'oud, amber, musky, powdery','unknown');
INSERT INTO "perf100" VALUES (23987,'https://www.fragrantica.com/perfume/yves-saint-laurent/rive-gauche-pour-homme-light-12445.html','rive-gauche-pour-homme-light','yves-saint-laurent','France','men',4.66,'2004','aromatic, fresh spicy, woody, green, citrus','unknown');
INSERT INTO "perf100" VALUES (23988,'https://www.fragrantica.com/perfume/shiseido/inoui-14382.html','inoui','shiseido','Japan','women',4.66,'1976','aromatic, woody, green, mossy, fresh spicy','unknown');
INSERT INTO "perf100" VALUES (23989,'https://www.fragrantica.com/perfume/al-wataniah/kayaan-classic-82472.html','kayaan-classic','al-wataniah','UAE','unisex',4.66,'2023','vanilla, white floral, rose, powdery','unknown');
INSERT INTO "perf100" VALUES (23990,'https://www.fragrantica.com/perfume/fragrance-world/aether-94702.html','aether','fragrance-world','UAE','unisex',4.66,'2024','woody, fruity, citrus, powdery, musky','unknown');
INSERT INTO "perf100" VALUES (23991,'https://www.fragrantica.com/perfume/orientica-premium/xclusif-oud-bleu-78036.html','xclusif-oud-bleu','orientica-premium','UAE','unisex',4.66,'2022','warm spicy, fresh spicy, woody, vanilla, powdery','unknown');
INSERT INTO "perf100" VALUES (23992,'https://www.fragrantica.com/perfume/sultan-pasha-attars/juriah-64538.html','juriah','sultan-pasha-attars','UK','unisex',4.66,'2019','rose, amber, animalic, floral, woody','sultan pasha');
INSERT INTO "perf100" VALUES (23993,'https://www.fragrantica.com/perfume/tru-fragrances/praline-pistachio-89498.html','praline-pistachio','tru-fragrances','USA','women',4.66,'2023','sweet, vanilla, coconut, nutty, caramel','unknown');
INSERT INTO "perf100" VALUES (23994,'https://www.fragrantica.com/perfume/phebo/bronze-intenso-70663.html','bronze-intenso','phebo','Brazil','unisex',4.66,'2021','powdery, woody, vanilla, amber, rum','alberto morillas');
INSERT INTO "perf100" VALUES (23995,'https://www.fragrantica.com/perfume/ojar/encens-cuivre-eau-de-parfum-87918.html','encens-cuivre-eau-de-parfum','ojar','Oman','unisex',4.66,'2023','amber, balsamic, warm spicy, woody, patchouli','jordi fern�ndez');
INSERT INTO "perf100" VALUES (23996,'https://www.fragrantica.com/perfume/godet/folie-bleue-47112.html','folie-bleue','godet','France','unisex',4.66,NULL,'woody, ozonic, citrus, warm spicy, aromatic','unknown');
INSERT INTO "perf100" VALUES (23980,'https://www.fragrantica.com/perfume/al-haramain-perfumes/haramain-detour-eco-92657.html','haramain-detour-eco','al-haramain-perfumes','UAE','unisex',4.65,NULL,'lavender, citrus, fresh spicy, aromatic, oud','unknown');
INSERT INTO "perf100" VALUES (23981,'https://www.fragrantica.com/perfume/guerlain/habit-rouge-l-extrait-31928.html','habit-rouge-l-extrait','guerlain','France','men',4.65,'2008','citrus, woody, amber, warm spicy, aromatic','thierry wasser');
INSERT INTO "perf100" VALUES (23982,'https://www.fragrantica.com/perfume/al-wataniah/amnia-88546.html','amnia','al-wataniah','UAE','unisex',4.65,'2022','white floral, vanilla, sweet, almond, tuberose','unknown');
INSERT INTO "perf100" VALUES (23983,'https://www.fragrantica.com/perfume/arabian-oud/amiri-77308.html','amiri','arabian-oud','Arabia saudi ','unisex',4.65,'2022','citrus, amber, powdery, woody, sweet','miroslav petkov');
INSERT INTO "perf100" VALUES (23984,'https://www.fragrantica.com/perfume/arabian-oud/kashmir-musk-69013.html','kashmir-musk','arabian-oud','Arabia saudi ','unisex',4.65,'2020','white floral, tuberose, musky, floral, animalic','unknown');
INSERT INTO "perf100" VALUES (23985,'https://www.fragrantica.com/perfume/boadicea-the-victorious/glistening-61426.html','glistening','boadicea-the-victorious','UK','unisex',4.65,'2018','oud, warm spicy, fresh spicy, metallic, patchouli','unknown');
INSERT INTO "perf100" VALUES (23986,'https://www.fragrantica.com/perfume/habibi-ny/white-moroccan-leather-68804.html','white-moroccan-leather','habibi-ny','USA','unisex',4.65,'2021','amber, woody, powdery, iris, leather','marion costero');
INSERT INTO "perf100" VALUES (23968,'https://www.fragrantica.com/perfume/guerlain/bouquet-de-paris-57878.html','bouquet-de-paris','guerlain','France','women',4.64,'2019','warm spicy, aromatic, floral, woody, smoky','thierry wasser');
INSERT INTO "perf100" VALUES (23969,'https://www.fragrantica.com/perfume/o-boticario/egeo-fresh-meli-93333.html','egeo-fresh-meli','o-boticario','Brazil','women',4.64,'2024','ozonic, aquatic, sweet, fresh spicy, fruity','unknown');
INSERT INTO "perf100" VALUES (23970,'https://www.fragrantica.com/perfume/ralph-lauren/tuxedo-11572.html','tuxedo','ralph-lauren','USA','women',4.64,'1979','amber, aromatic, white floral, woody, yellow floral','unknown');
INSERT INTO "perf100" VALUES (23971,'https://www.fragrantica.com/perfume/zara/white-soho-57107.html','white-soho','zara','Spain','men',4.64,'2019','iris, woody, musky, floral, powdery','j�r�me epinette');
INSERT INTO "perf100" VALUES (23972,'https://www.fragrantica.com/perfume/granado/fervo-intenso-92930.html','fervo-intenso','granado','Brazil','unisex',4.64,'2024','woody, warm spicy, cacao, powdery, amber','benoist lapouza');
INSERT INTO "perf100" VALUES (23973,'https://www.fragrantica.com/perfume/coty/chypre-6072.html','chypre','coty','USA','women',4.64,'1917','citrus, earthy, woody, floral, mossy','francois coty');
INSERT INTO "perf100" VALUES (23974,'https://www.fragrantica.com/perfume/fragrance-world/cocktail-intense-95180.html','cocktail-intense','fragrance-world','UAE','unisex',4.64,'2021','warm spicy, vanilla, woody, sweet, amber','unknown');
INSERT INTO "perf100" VALUES (23975,'https://www.fragrantica.com/perfume/the-woods-collection/dusk-63711.html','dusk','the-woods-collection','France','unisex',4.64,'2020','warm spicy, vanilla, aromatic, woody, fresh spicy','unknown');
INSERT INTO "perf100" VALUES (23976,'https://www.fragrantica.com/perfume/happyland/happyland-signature-57435.html','happyland-signature','happyland','USA','unisex',4.64,'2019','sweet, tobacco, honey, cinnamon, amber','e.j. wells');
INSERT INTO "perf100" VALUES (23977,'https://www.fragrantica.com/perfume/ermenegildo-zegna/mediterranean-neroli-eau-de-parfum-74060.html','mediterranean-neroli-eau-de-parfum','ermenegildo-zegna','Italy','men',4.64,NULL,'amber, citrus, white floral, warm spicy, aromatic','unknown');
INSERT INTO "perf100" VALUES (23978,'https://www.fragrantica.com/perfume/caron/nuit-de-noel-extrait-de-parfum-34198.html','nuit-de-noel-extrait-de-parfum','caron','France','women',4.64,'1922','woody, yellow floral, rose, amber, powdery','ernest daltroff');
INSERT INTO "perf100" VALUES (23979,'https://www.fragrantica.com/perfume/bortnikoff/oud-maximus-autumn-2019-59461.html','oud-maximus-autumn-2019','bortnikoff','Thailand','unisex',4.64,'2019','oud, rose, warm spicy, citrus, floral','dmitry bortnikoff');
INSERT INTO "perf100" VALUES (23958,'https://www.fragrantica.com/perfume/dior/dior-homme-original-69010.html','dior-homme-original','dior','France','men',4.63,'2021','iris, earthy, aromatic, warm spicy, powdery','fran�ois demachy');
INSERT INTO "perf100" VALUES (23959,'https://www.fragrantica.com/perfume/givenchy/les-parfums-mythiques-insense-1976.html','les-parfums-mythiques-insense','givenchy','France','men',4.63,'2007','woody, green, aromatic, floral, fresh spicy','unknown');
INSERT INTO "perf100" VALUES (23960,'https://www.fragrantica.com/perfume/givenchy/organza-indecence-eau-de-toilette-du-desert-42010.html','organza-indecence-eau-de-toilette-du-desert','givenchy','France','women',4.63,'2006','fruity, amber, citrus, warm spicy, sweet','unknown');
INSERT INTO "perf100" VALUES (23961,'https://www.fragrantica.com/perfume/guerlain/quand-vient-la-pluie-2618.html','quand-vient-la-pluie','guerlain','France','women',4.63,'2007','powdery, white floral, sweet, violet, citrus','sylvaine delacourte, thierry wasser');
COMMIT;
